# Generated by Django 5.2.5 on 2025-08-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
