# Generated by Django 5.2.5 on 2025-08-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Upload resource file (optional)', null=True, upload_to='lecture_files/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file ', null=True, upload_to='lecture_videos/'),
        ),
    ]
