# Generated by Django 5.2.5 on 2025-08-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lecture_resource_file_lecture_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('business', 'Business'), ('finance_accounting', 'Finance & Accounting'), ('it_software', 'IT & Software'), ('office_productivity', 'Office Productivity'), ('personal_development', 'Personal Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('lifestyle', 'Lifestyle'), ('photography_video', 'Photography & Video'), ('health_fitness', 'Health & Fitness'), ('music', 'Music'), ('teaching_academics', 'Teaching & Academics')], default='development', max_length=50),
        ),
    ]
